version: '3'

services:
  blog-api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - blog-data
  blog-data:
    image: postgres:14
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: kanybek
      POSTGRES_PASSWORD: kany2005
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
